<?php echo $this->headScript()->appendFile($this->websiteUrl . 'plugins/backstretch/system/layout/js/jquery.backstretch.min.js'); ?>
<script>
    var images = [];
	<?php foreach($this->images as $img): ?>
		images.push('<?php echo $img; ?>');
	<?php endforeach; ?>
    var index = 0;

    $.backstretch(images[index], {speed: <?php echo (($this->time) ? $this->time : Backstretch::DEFAULT_FADE_INTERVAL); ?>});

    setInterval(function() {
        index = (index >= images.length - 1) ? 0 : index + 1;
        $.backstretch(images[index]);
    }, 5000);
</script>