<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>

<script>
    var images = [];
	<?php foreach($this->images as $img): ?>
		images.push('<?php echo $img; ?>');
	<?php endforeach; ?>
    var index = 0;

    $.backstretch(images, {
        centeredY: true,
        centeredX: true,
        duration: <?php echo (($this->duration) ?: Backstretch::DEFAULT_DURATION_INTERVAL); ?>,
        fade: <?php echo (($this->time) ?: Backstretch::DEFAULT_FADE_INTERVAL); ?>
    });
</script>